CREATE SCHEMA UVV_CC3M;

USE UVV_CC3M;
#TABELA DO BANCO
CREATE TABLE IF NOT EXISTS BANCO(
#ATRIBUTOS DO BANCO - TIPO - RESTRIÇÕES
BANCO_ID INT PRIMARY KEY,
BANCO_NUM VARCHAR(20) NOT NULL,
BANCO_AGEN VARCHAR(20) NOT NULL,
BANCO_SALDO DECIMAL(10,2) NOT NULL
);

#TABELA DA EMPRESA
CREATE TABLE IF NOT EXISTS EMPRESA(
EMP_ID INT PRIMARY KEY,
EMP_NOME VARCHAR(100) NOT NULL,
EMP_TIPO VARCHAR(50) NOT NULL,
EMP_CNPJ_CPF CHAR(14) NOT NULL
);

#TABELA PAGAR
CREATE TABLE IF NOT EXISTS PAGAR(
PAG_ID INT PRIMARY KEY,
PAG_VALOR DECIMAL(10,2) NOT NULL,
PAG_DATA_PREV DATE NOT NULL,
PAG_STATUS VARCHAR(20) NOT NULL,
EMP_ID INT NOT NULL,
BANCO_ID INT NOT NULL,
constraint FK_EMP_ID foreign key (EMP_ID) references EMPRESA (EMP_ID),
constraint FK_BANCO_ID foreign key (BANCO_ID) references BANCO (BANCO_ID)
);

#TABELA RECEBER
CREATE TABLE IF NOT EXISTS RECEBER(
REC_ID INT PRIMARY KEY,
REC_VALOR DECIMAL(10,2) NOT NULL,
REC_STATUS VARCHAR(20) NOT NULL,
EMP_ID INT NOT NULL,
BANCO_ID INT NOT NULL,
constraint FK_EMP_ID foreign key (EMP_ID) references EMPRESA (EMP_ID),
constraint FK_BANCO_ID foreign key (BANCO_ID) references BANCO (BANCO_ID)
);
